### ISSUE TITLE
Bug: declaration files imports path referencing other bundle declaration files are wrong

### ISSUE THREAD

**Issue by marcalexiei** [unplugin/unplugin-isolated-decl#23]
### Describe the bug

Using `preserveModules` option there is a problem when generated declaration files reference other types included in other declarations files:

Basically all declaration files are wrapped inside a folder named `index.d.ts`.
However when a file tries to import another file included in the same bundle the path to this file is wrong:
it usually miss a `..` segment to exit the "wrapper" folder.

More information can be found in the reproduction repository.

### Reproduction

https://github.com/marcalexiei/unplugin-isolated-decl-bugs/tree/nested-declarations

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 9.57 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://github.com/unplugin/unplugin-isolated-decl/issues/25#issuecomment-2386602670

**Comment by marcalexiei** [comment]
A few tweaks in the rollup config solved the problem:

```diff
export default defineConfig({
-  input: {
-    a: "src/a/index.ts",
-    b: "src/b/index.ts",
-  },
+  input: ["src/a/index.ts", "src/b/index.ts"],
   output: {
     dir: "dist",
     format: "es",
-    entryFileNames: "[name]/index.js",
     preserveModules: true,
   },
   plugins: [UnpluginIsolatedDecl(), swc()],
});
```

---

```js
// rollup.config.js
export default defineConfig({
  input: ["src/a/index.ts", "src/b/index.ts"],
  output: {
    dir: "dist",
    format: "es",
    preserveModules: true,
  },
  plugins: [UnpluginIsolatedDecl(), swc()],
});
```
