### ISSUE TITLE
Typescript path alias not resolved in emited declarations

### ISSUE THREAD

**Issue by pradel** [unplugin/unplugin-isolated-decl#25]
### Describe the bug

Hi, I am integrating this plugin and found out that the typescript path alias are not resolved in the emited declarations.

If in your code you write
```ts
import { a } from "@/utils";
export { a };
```
with the following ts paths config

```
"paths": {
        "@/*": ["./src/*"]
      },
```

The .d.ts file as the same output

```ts
import { a } from "@/utils";
export { a };
```

What I would be expecting is that the path is resolved to produce a valid declaration file like this

```ts
import { a } from "./utils";
export { a };
```

The result is that the emited declarations are not working in packages importing them as they don't know how to resolve the paths alias.

### Reproduction

https://codesandbox.io/p/devbox/issue-isolated-declarations-paths-39pdg8

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 1.75 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/share/npm-global/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Path alias will not be resolved even if you're using native `tsc`.

**Comment by pradel** [comment]
Interesting, I just tried with tsc and indeed the same is happening, do you know why? The declarations for packages that consume them are invalid.
And is there any workaround to get it to work with this plugin?

**Comment by sxzz** [comment]
Essentially, this issue faces the same problem as #23; dts packaging cannot leverage rollup/esbuild's own path resolver/rewriter. I haven't thought of a good solution yet 🤔

**Comment by marcalexiei** [comment]
Gotcha, thanks for your review on #23.
just to add some context: 
I'm trying to migrate my build toolchain to `swc` and `unplugin-isolated-decl` from `@rollup/plugin-typescript`.

> dts packaging cannot leverage rollup/esbuild's own path resolver/rewriter

With the typescript plugin the declaration were emitted in the original folder (relative to the module root) so they were not included inside the folder with the `index.js` file. 

To better explain what I'm talking about I created a small example here: 
https://github.com/marcalexiei/unplugin-isolated-decl-bugs/tree/nested-declarations-with-ts

>  I haven't thought of a good solution yet 🤔

Maybe the typescript plugin approach could be used to solve both these issues.

---

Probably you are already aware of all this, but I just want to help with the little I know so far 😅

**Comment by sxzz** [comment]
Added an new option `rewriteImports`, see https://github.com/unplugin/unplugin-isolated-decl#rewriteimports
