### ISSUE TITLE
sourceMap: false is not being respected

### ISSUE THREAD

**Issue by brc-dd** [unplugin/unplugin-isolated-decl#42]
### Describe the bug

`UnpluginIsolatedDecl({ transformer: 'oxc', sourceMap: false })` still emits `index.d.ts.map`

Might be an issue with oxc, typescript transformer works fine 👀 

### Reproduction

- Clone https://github.com/brc-dd/oxc-id-sourcemap-issue
- Run `rm -rf dist && node build.mjs`
- There is `index.d.ts.map` in dist directory.

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 388.44 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/1482_1733160171083/bin/node
    Yarn: 1.22.22 - ~/.local/state/fnm_multishells/1482_1733160171083/bin/yarn
    npm: 10.9.0 - ~/.local/state/fnm_multishells/1482_1733160171083/bin/npm
    pnpm: 9.14.4 - ~/.local/state/fnm_multishells/1482_1733160171083/bin/pnpm
    bun: 1.1.38 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 18.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Looks like it's a bug in Oxc 🤔
